version: "3.8"
services:
  rest:
    build: ./
    ports:
      - "127.0.0.1:8080:8080"


  db:
    image: "postgres"
    expose: 
      - 5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    volumes: 
      - database_data:/var/lib/postgresql/data
      - ./create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql

volumes:
  database_data:
    driver: local